name: Tag git version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git tag
        run: |
          git tag $(cat VERSION)
          git push --tags